image: circleci/ruby:2.5-node-browsers

# Ideally service versions should be kept in sync with production
services:
  - postgres:9.5
  - redis:3.2

variables:
  POSTGRES_DB: tariff_management_test

cache:
  key: ${CI_JOB_NAME}-v1
  paths:
  - vendor/ruby

test:
  variables:
    DATABASE_URL: postgresql://postgres:postgres@postgres:5432/$POSTGRES_DB
    REDIS_URL: redis://redis:6379
    RAILS_ENV: test
    GOVUK_APP_DOMAIN: test
  script:
  - sudo apt-get update -qq && sudo apt-get install -y postgresql
  - bundle install --path vendor --jobs=4 --retry=3
  - bundle exec rake db:drop db:setup
  - bundle exec rake assets:precompile
  - bundle exec rspec
