version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
      - image: circleci/postgres:9.6.2
      - image: circleci/openjdk:8
      - image: elasticsearch:5.3
      - image: redis:3.2.11
    environment:
      - GOVUK_APP_DOMAIN: test
    steps:
      - checkout
      - run:
          name: Install bundler
          command: gem install bundler
      - run: bundle install
      - run:
          name: "Run Rspec"
          command: |
            bundle exec rspec --profile 10 \
                              --format RspecJunitFormatter \
                              --out test_results/rspec.xml \
                              --format progress \
                              $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)
      - deploy:
          command: |
            curl -v -L -o cf-cli_amd64.deb 'https://cli.run.pivotal.io/stable?release=debian64&source=github'
            sudo dpkg -i cf-cli_amd64.deb
            cf -v
      - deploy:
          command: |
            curl -v -L -o autopilot https://github.com/contraband/autopilot/releases/download/0.0.3/autopilot-linux
            chmod +x autopilot
            cf install-plugin autopilot -f
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ];
              then CF_SPACE=development CF_APP=tariff-backend-dev CF_APP_WORKER=tariff-backend-worker-dev ./bin/deploy
            fi
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "staging" ];
              then CF_SPACE=staging CF_APP=tariff-backend-staging CF_APP_WORKER=tariff-backend-worker-staging ./bin/deploy
            fi
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "production" ];
              then CF_SPACE=production CF_APP=tariff-backend-production CF_APP_WORKER=tariff-backend-worker-production ./bin/deploy
            fi
