development:
  adapter: postgresql
  encoding: utf8
  reconnect: true
  database: tariff_development
  single_threaded: true
  username: tariff
  password: tariff
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  reconnect: true
  database: tariff_test
  single_threaded: true
  username: tariff
  password: tariff
  host: localhost
