development:
  adapter: mysql2
  encoding: utf8
  reconnect: true
  database: tariff_development_v2
  pool: 5
  username: tariff
  password: tariff

test:
  adapter: mysql2
  encoding: utf8
  reconnect: true
  database: tariff_test
  pool: 5
  username: tariff
  password: tariff
