development:
  adapter: mysql2
  encoding: utf8
  reconnect: true
  database: tariff_development
  max_connections: 5
  username: tariff
  password: tariff

test:
  adapter: mysql2
  encoding: utf8
  reconnect: true
  database: tariff_test
  max_connections: 1
  username: tariff
  password: tariff
