default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV['DB_POOL'] || ENV['MAX_THREADS'] || 5 %>

development:
  <<: *default
  database: tariff_development

test:
  <<: *default
  database: tariff_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
