development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: trade_tariff_development
  pool: 5
  username: root
  password:

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: trade_tariff_test
  pool: 5
  username: root
  password:
