development:
  adapter: mysql2
  encoding: utf8
  reconnect: true
  database: trade_tariff_development
  pool: 5
  username: root
  password: 

test:
  adapter: mysql2
  encoding: utf8
  reconnect: true
  database: trade_tariff_test
  pool: 5
  username: trade_tariff
  password: trade_tariff
