:verbose: false
:concurrency:  1
:queues:
  - [default, 5]
:schedule:
  #
  # Syntax:
  #
  # mm hh dd mt wd  command
  #
  # mm minute 0-59
  # hh hour 0-23
  # dd day of month 1-31
  # mt month 1-12
  # wd day of week 0-7 (Sunday = 0 or 7)
  #
  # Online converter: https://crontab.guru/#0_22_*_*_*
  #
  # Example:
  #
  # AnyWorkerNameHere: # from app/workers
  #   cron: "0 22 * * *" # 10 PM every days
  #   description: ""
